### ISSUE TITLE
HIP31: Governance by Token Lock

### ISSUE THREAD

**Issue by jamiew** [helium/HIP#183]
**Author(s):** @tjain-mcc, Shayon Sengupta
**Start Date:** 2021-04-19
**Category:** Governance (AKA `Meta`)
**Initial PR:** [#182](https://github.com/helium/HIP/pull/182)
**Tracking Issue:** this
**Status**: In Discussion
**Discord channel**: #hip-31-governance-by-token-burn on https://discord.gg/helium

**Rendered view:**

https://github.com/helium/HIP/blob/master/0031-governance-by-token-lock.md

**Summary:**

We propose a new governance system where voters must burn their HNT in order to vote. This system helps encourage consensus building because contentious votes are more expensive than landslides. It also imposes a significant cost on any large holder which tries to control governance, leading to less oligarchic governance outcomes.

**Comment by bellapretta** [comment]
I purchased three bobcat miners in April and have not received them yet, and currently do not own any HNT but I like this project a lot. How much HNT would you suggest be burned per person voting?

**Comment by jamiew** [comment]
@bellapretta please read through the proposal. It depends.

**Comment by bellapretta** [comment]
Jamie W
 thanks for responding to me, it was lazy of me not to read your voting proposal, and now that I have and I still might not fully understand it, I am very not a computer savey, but I would vote no on your proposal event though I agree with your premise that members should have some skin in the game to vote. It seems odd, that the winners voting group would receive their HNT back and the losers HNT burned, as well as the value of the vote diminishes with time the closer to the end of the designated voting time period. 

One HNT one vote per wallet address, burn after closing the voting period.

**Comment by jamiew** [comment]
This was essentially entirely re-thought and re-written by #252 

I've updated links throughout the repository and the name of the channel in Discord

**Comment by shortonnyc** [comment]
You would need a 100,000 HNT bond to submit a HIP?

**Comment by curiousfokker** [comment]
Dig the work to tackle a thorny issue so far, thank you all!

1) Who's going to put up 100k HNT to submit a HIP?  That seems awfully high.  Could para1 have put that up?  Even for a group, that's an awful lot.  10k HNT seems like a more reasonable amount.  If someone/group has put up 100k HNT just to propose a HIP, there's a giant incentive for them to get it to run through, including being disingenuous about how it works/what it does.  

2)  If a vote is close it probably means both sides have good reason to believe they're right.  I don't see how locking up tokens for a long time on a close vote does the network any good, or promotes general goodwill.  Is it solely a useful defense mechanism against hostile actors?  

3) I'd like to incentivize *informed* voting.  Can we incentivize a test to make sure a voter understands what they're voting on?

Let's say we're voting on issue xyz.    There are 2 solutions, A and B.  Voting is split reasonably evenly, and both sides are passionate.  

It's more likely an indication that the community needs a third option rather than settling on just the 2 proposed.  What we should probably be looking for instead of ways to disincentivize a close vote is to strongly encourage a mechanism for finding alternate solutions.

Perhaps a pre-vote system?  Say you had a pre-vote that was close, sort of a test run.  The closer the test vote is, the stronger the incentive to come up with a new solution; perhaps by pulling from the initial bond to reward "third solution" providers/proposals?

**Comment by curiousfokker** [comment]
Another thing to consider is giving weight to Hotspot owners;  1 vote - 1 hotspot, and perhaps something that gives more power to hotspot owners, i.e. 1 hotspot = 5 HNT worth of voting.  Not sure how to balance out whales with that, but seems that we should leverage the fact that people have gone to some kind of physical effort to participate in the Network.  More than just tokens.

**Comment by cvolkernick** [comment]
Is there a latest update on this @jamiew et al...? Looks like the convo has kind of sputtered out a bit since original proposal (understandable as network stability a la technical fundamentals takes precedence over governance in the short term). TIA!

**Comment by vincenzospaghetti** [comment]
Hi - this HIP is more than a year old. Since this HIP, there have been other ideas and implementations of token voting (with vote escrowed HNT). Is it fine to close this HIP and the corresponding channel? @tjain-mcc
