### ISSUE TITLE
Mechanism for hotspots attached to lost wallets?

### ISSUE THREAD

**Issue by shawaj** [helium/HIP#213]
Sorry if this is the wrong place for this, if it is then please let me know and I'll happily move it.

We have had one or two customers who have onboarded their hotspot to their wallet and have subsequently lost the seed phrase to their wallet.

Currently, these devices are essentially bricked but it is possible for us to rework them (for a fee) and fix the unit to allow it to be re-onboarded by replacing the ECC chip.

We could do this with no problems, however, given this brings in concerns about theft, among other things, we felt this would need a mechanism to be agreed on with DeWi and the wider community in order to safeguard the network from theft and gaming.

I guess the two things I was thinking would be needed are:

1. A method to verify the hotspot has not been stolen (proof of ID and purchase etc)
2. A method to blacklist/remove the original ECC key from the network

With these two things it should be ok, in my opinion, but maybe there's something I'm missing of course. And for a fee of around £100 would be less than a full replacement hotspot. It obviously also solves an issue of sustainability that will likely come up more frequently as time passes.

**Comment by jamiew** [comment]
Interesting problem. Would you be willing to write this up as a formal HIP? This kind of key rejection/denylist you're talking about has been discussed for a while, primarily re. anti-cheating, but this repository is intended just for HIPs rather than as an open discussion forum. 

More info in HIP7 [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

**Comment by jamiew** [comment]
Per my standard protocol gonna mark as `invalid` and close but please feel free to continue the discussion

**Comment by Pizzafoodgr** [comment]
HELLO, I have 2 helium bobcat miners that were hooked up to wallet and never able to hook up to mine because of stupid mistakes I made when starting to learn how to mine 2 years ago and I dont have my wallet seed phrase and was reading that u mite be able to change the chip? Are u able to? And how much for 2 miners? Thank you and I know this is stupid that's it happened.

**Comment by madninja** [comment]
> HELLO, I have 2 helium bobcat miners that were hooked up to wallet and never able to hook up to mine because of stupid mistakes I made when starting to learn how to mine 2 years ago and I dont have my wallet seed phrase and was reading that u mite be able to change the chip? Are u able to? And how much for 2 miners? Thank you and I know this is stupid that's it happened.

This is not the place for this discussion/question. Please join discord and ask for help there.. In general if you've lost your seedphrase to your wallet there is nothing anyone can do to help. Either way, please ask in Discord
