### ISSUE TITLE
HIP 57: PoC Rewards Establishment Period

### ISSUE THREAD

**Issue by edakturk14** [helium/HIP#376]
# HIP 57: PoC Rewards Establishment Period

- Author(s): [@Scottsigel](https://github.com/Scottsigel), [@starwatcher](https://github.com/mrpatrick1991), [@jthiller](https://github.com/jthiller)
- Start Date: 2022-03-16
- Category: Technical
- Original HIP PR: https://github.com/helium/HIP/pull/375
- Tracking Issue: https://github.com/helium/HIP/issues/376 (this)
- Status: In Discussion

# Summary
[summary]: #summary

In order to combat PoC rewards gaming, the process of ‘spoofing’ or ‘gaming’ a Hotspot to earn disproportionate rewards must be economically unsound. Among a range of solutions, the existing denylist and HIP-40 offer a means to remove Hotspots that don’t provide legitimate coverage. However, there is sufficient time after onboarding a Hotspot where it remains economically viable to spoof a location and game PoC rewards before a Hotspot in question can be confidently identified and added to a denylist.

If approved, this proposal would introduce a Hotspot ‘establishment period’ such that the network can better learn about a Hotspot’s deployment immediately following a location assertion. This period would be defined initially as 15 days and 10 successful witnesses, as set by a chain variable. A Hotspot’s PoC rewards and witnesses of its beacons would be throttled to 10% of what would be its normal earnings until both of these conditions are met. Data rewards would be unaffected. As the network improves its ability to understand a Hotspot’s location or as reliance on denylists are reduced, these chain variables could be adjusted. 

# Rendered View

https://github.com/helium/HIP/blob/main/0057-poc-rewards-establishment-period.md

**Comment by edakturk14** [comment]
This HIP draft has been numbered and merged for discussion as HIP `57`. 

Please direct future questions & comments to the new tracking issue: #376

If you are one of the named authors, please include `#376` in future pull requests to have them automatically merged.

**Comment by mkultr44** [comment]
For people with really good locations and coverage, the very thing you want to incentivice, that would increase the ROI by about 50% though......

**Comment by alphaqt** [comment]
This seems like a bandaid.  The real problem is that there is no method currently to actually validate the location of a Hotspot.  The companies that manufacture Helium Miners should start including a GPS receiver to accurately record a hotspots true location to keep people from asserting a location different than the physical hotspot.  Once there are enough hotspots with GPS coordinates, the remaining hotspots could be easily located via triangulation of the beacons.  We need to move away from bandaids and towards solutions that elevate the Miner network to one that is impervious to scamming.

**Comment by mkultr44** [comment]
you can spoof gps too, wouldn't change anything

**Comment by wolfenhawke** [comment]
I think the way to increase the reliability of this is to use time. With time we know which hotspots are not on a deny list, are true, and even what their average behavior is like. When a new miner comes online, a time and witness window can be used _along with this historic information_ to validate what is being seen. 
Someone being honest for 15 days then being dishonest? The algorithm can see when the change occurs that the new witness pattern is an anomaly. Someone self witnessing with a bunch in the basement? History wouldn't have the bunch in the basement. 
Then the gaming is looking for those nests where maybe a spoofer was able to get many in the network and looking like normal -- but even then, it will show up because once legitimate units reach the area suddenly a whole nest is not being witnessed like they should be.
Time as in average of continuous operation is like integrating over a long period - it provides an interesting additional dimension of information.

**Comment by butter14** [comment]
This is a good idea, but it needs "teeth". Proper validation using other methods will be needed to prove Hotspot locations.

**Comment by vincenzospaghetti** [comment]
This HIP has been stale for some time. We are moving to close it, as there as been no more discussion in the community Discord. If you would like to reopen this HIP, please submit a new PR with changes. Thanks for your contribution to the Helium Community!
