### ISSUE TITLE
HIP 58: PoC Distance Limit

### ISSUE THREAD

**Issue by edakturk14** [helium/HIP#384]
## HIP 58: PoC Distance Limit

- Author(s): [@abhay](https://github.com/abhay), [@mrpatrick1991](https://github.com/mrpatrick1991), et al
- Start Date: 2022-04-02
- Category: Technical
- Original HIP PR: https://github.com/helium/HIP/pull/381
- Tracking Issue: https://github.com/helium/HIP/issues/384 (this)
- Status: Approved

## Summary

The Proof-of-Coverage incentive model is crucial to the ongoing growth of the
Helium Network. As the network grows, efforts to prevent Proof-of-Coverage
gaming must be bolstered in order to encourage honest Hotspot deployment. One
known gaming technique works by altering the information provided by beacon and
witness packets to increase reported distances. This can make it appear that
Hotspots provide coverage where they do not. An effective way to reduce the
impact of this attack is to place an upper limit on the distance at which
witnesses for hotspots will be considered valid by the blockchain and thus be
considered for rewards. 

When PoCv11 was developed, a witness distance limit feature was written but
never activated. If approved, this proposal would impose a `100 km` limit to
Proof-of-Coverage witnessing and this value can be modified further through
governance in the future. Witnesses where the asserted distance is greater than
100 km would be marked invalid by the Challenger. This limit is further
supported by the fact that most sensor deployments have a practical maximum
distance of 30-50km. Although a Helium Hotspot may be able to see PoC beacons
greater than 100 km, there are no current use cases at this range.

## Rendered View

https://github.com/helium/HIP/blob/main/0058-poc-distance-limit.md

**Comment by TPPSupport** [comment]
We need to get this HIP up for vote immediately, the gamers have destroyed this ecosystem and will be the downfall of Helium

**Comment by grawi-sikorsky** [comment]
Sounds good to me.

**Comment by Devebir** [comment]
I'm sorry for all of you but i hope this HIP isn't going to be effective, because there are people (like me) who have no chance if not tuning the setup to witness hotspot at 100+ km. In my case i had to spend hundreds of euros to build a set-up to reach the only hotspots available in my area, and those are ~110km away (i have no way to move the miner).

**Comment by untotren** [comment]
How about you start having manufacturers include a $2 GPS chip.....

**Comment by curiousfokker** [comment]
Hi Untotren, that's not effective because GPS is easy to spoof.

**Comment by Bixbit021** [comment]
Hi, I know some who has invester a lot in antennas and height for reach over 100km (closest city). I'm not against HiP58 but one solution to this exclusion of people is an application process for those who have setups with +100km reach. Then these applications must be handled manually by people working for Helium. 

Any other ideas?

**Comment by Elexy** [comment]
I started with 2 hotspots in an area where there was virtually no coverage. I upgraded my antennas in order to make it worth my while, until more hotspots appear in the area. This proposal would penalize me and others who start deploying in remote areas. I was under the impression that heliums goal is to provide as much coverage as possible. Just putting a hard limit on the kilometers is to one sided. I think it should be taken into account how many hotspots are in the vicinity.

**Comment by curiousfokker** [comment]
100 km is completely reasonable.  Remember, the network is about coverage, not earning from gateway<-->gateway communication.  There is zero utility in optimizing (or even encouraging) 100km plus communications.  It's like optimizing all cars on the road to be F1 capable.  Focus on network utility; that's the prize.

**Comment by lketchersid** [comment]
This proposal looks at past history and not future deployments. A vast majority of the hotspots are in urban areas. My team and I are doing deployments in rural areas to deploy sensors for monitoring regenerative agriculture. There is no coverage. Thus we have to deploy at least two off-grid hotspots as we are building coverage so that there will be witnesses. Depending on the landscape (flat versus hilly) we will be testing a variety of antennas to get as much coverage as we can. 

The 100km distance seems arbitrary. I want the spoofers/gamers gone as well, but not with an arbitrary limit that looks at past history and not at expanding coverage.

**Comment by alphaqt** [comment]
There could be another possibility.  Instead of limiting the distance, why not rank order the witnesses according to distance.  Ultimately, this would give preference to closer hotspots rather than those that are a long distance away and possibly spoofing.  We need to begin a gradual change towards providing a useful network.  Hotspots that are a long distance away create unnecessary interference and provide unreliable coverage as devices move around.

**Comment by grawi-sikorsky** [comment]
Hey, i have some quick thought about gamblers - maybe not relating to this HIP, but worth to discuse/criticize.
I explored HIP catalog on github and found HIP57 where someone upload screenshot of some obvious gambler: 24h earnings is about 33HNT.
Amount looks crazy - for many of peeps who deploy legit, reasonable installs it'll take 3-6 months to reach that. For those who are less focused on coverage - maybe year.

Quick math: 700'000 hotspots which 75% of them are online gives us ~525'000 working hotspots.
This one gambler tooks about 750$ rewards in one day for all of us legit users.
So: 750$ / 525'000 = 0,0014$
Looks pretty small right? Yes, but there are many more of those gamblers in project. I don't have any data and numbers how many those gambling hotspots earing. yet denylist shows 19k adresses (some of them are accounts, some hotspots).
Let's say there are just 1000 of them making similar earnings and we all are robbed for about 0.14$ / day.
Yeah i know, still not much but it's all about scale.

**Getting to the point**: In explorer API shows us average network earnings for every day..
We all know that at some point earnings looks more like cheating than normal setups.

**Isn't it good idea to set fixed or dynamicaly calculated multiplier of maximum earnings per 24 hours?**

That kind multiplier, even set at 20x, based on 0.1 HNT / day average, gives us roughly 2HNT / day maximum reward.
I'm fresh in this project with only 4 hotspots, but as far as i see, 2HNT / day is now unreachable even for best setups.
And far less than best gamblers can make (like that one from HIP57 image).
Am I missing something with this concept? Isn't it good solution to cut cheaters rewards until some better brains will figure out how to stop this?
Regards!

**Comment by abhay** [comment]
> **Isn't it good idea to set fixed or dynamicaly calculated multiplier of maximum earnings per 24 hours?**

If framed as a sanity check, then I think someone could write this HIP and propose it to the community. I’d have some implementation concerns but worth a discussion.

Probably not worth an ongoing discussion here, though, as it’s off topic. Maybe the poc-discussion or improvement proposals channels in Discord.

**Comment by curiousfokker** [comment]
Are there any examples of how many Hotspots earn the majority of their earnings from Hotspots over, say, even 50 km away?  I know early on para1 had shown the vast majority of earnings come from hotspots within a 10 km radius.

I know a bunch of you think you're really getting penalized here, but I'm curious as to what the data tells us.

To lketchersid's point, for ag and rural deployments, the 100 km limit isn't your issue, it's that there aren't other Hotspots within a **much** shorter range.  Connections over 30 km look sexy on the map, but they're unreliable both for earnings and for data transmission.  

I'd focus on the benefits of providing coverage and, as crazy as it sounds, ignore the rapidly diminishing PoC incentives.  If indeed you're looking to the future, you know that with 3 million Hotspots online within a year there is not a strong financial case to provide coverage solely to earn on PoC.  You're ahead of the game, mug.  ;) 

Look at any deployment and get the average distance of earning PoC connections; it'll be way less than 100km.  I'd propose we dial this down even further, to 50 km.  

You'd have to really have a funky edge case for the 100km limit to actually penalize you , like being over 100 km from a large number of Hotspots and have clear line of sight to that place.

**Comment by evandiewald** [comment]
@curiousfokker Great question. there are about 5000 hotspots (out of 700,000, or ~0.7%) for whom >50% of their witness receipts come from beaconers **more than 50km** away. From those 5000, more than 1 in 5 are currently on the denylist.

![image](https://user-images.githubusercontent.com/37876940/162645257-67091c79-c5f4-4aa7-802b-55008e3a5b68.png)

**Comment by ilovespectra** [comment]
I’d love to propose 125km because my mountaintop offgrids are being plagued by invalids now. 125km won’t help spoofers and I’m not witnessing any further than that anyway. I’d hate for this to negatively impact some of the best miner setups out there.

**Comment by Crisatian** [comment]
Can anyone explain to me why it gives me a disability if we are from the same hex?

**Comment by modestos** [comment]
> Are there any examples of how many Hotspots earn the majority of their earnings from Hotspots over, say, even 50 km away? I know early on para1 had shown the vast majority of earnings come from hotspots within a 10 km radius.
> 
> I know a bunch of you think you're really getting penalized here, but I'm curious as to what the data tells us.
> 
> To lketchersid's point, for ag and rural deployments, the 100 km limit isn't your issue, it's that there aren't other Hotspots within a **much** shorter range. Connections over 30 km look sexy on the map, but they're unreliable both for earnings and for data transmission.
> 
> I'd focus on the benefits of providing coverage and, as crazy as it sounds, ignore the rapidly diminishing PoC incentives. If indeed you're looking to the future, you know that with 3 million Hotspots online within a year there is not a strong financial case to provide coverage solely to earn on PoC. You're ahead of the game, mug. ;)
> 
> Look at any deployment and get the average distance of earning PoC connections; it'll be way less than 100km. I'd propose we dial this down even further, to 50 km.
> 
> You'd have to really have a funky edge case for the 100km limit to actually penalize you , like being over 100 km from a large number of Hotspots and have clear line of sight to that place.

There are many deployments in insular and rural areas that need that kind of coverage. This limit totaly kills e.g. marine, multi island /inter-insular applications of the network.

**Comment by edakturk14** [comment]
The HIP has been approved via heliumvote, with [+92%](https://heliumvote.com/14KhDJUdvAXNVVP5m5cqEaLGNC859sXvpHtxWX9r999pZKC8xAs) voting For HIP 58.

On behalf of Helium Foundation, the HIP Editors, and the wider Helium community, I am marking this proposal as approved and recommending that the coredev team implement the necessary changes as soon as reasonably possible.

**Comment by gandra01** [comment]
Hello. I dont have issue with limiting 100km but im facing issue with that. Like when i send beacon i am getting invalid witnesses because 100km plus hotspots catch it and i am loosing reward. Hotspots over 100km should not participate in hearing beacon if they are 100km or more km away. Like mine example i have plenty hotspots around me to reach 14/14 valids and instead im geting 7/14 valids because hotspots over 100km wins for witness. Just localy under 5km i have 15 hotspots around and i know that they can witness me but instead they dont witness mine beacon but others above 100km does and in same.time i am loosing reward and hotspots under 100km. 

Mine proposal is when beacon is being send all of those hotspots above 100km should not participate at all for being valid to catch it and win witness.

**Comment by vincenzospaghetti** [comment]
This HIP has been approved, and we are going to close this issue. Congrats on a successful HIP and for your contributions to the Helium Community!
