### ISSUE TITLE
HIP-58 Poc distance limit incrase to 200 km

### ISSUE THREAD

**Issue by Bcagatay53** [helium/HIP#389]
Change the distance limit to 200 
For example , i have 3 hotspots and in my state totally 9 hotspots. On the other hand there is a city, it’s 140 km far away and there are too many hotspots in there.  In my cities hotspots sends beacon to other city mostly , and our hotspots witnesses other cities hotspots. So too many transaction are invalid. And i see in your denylist chart, cheaters witness distance is starts at 200 km mostly. So its clear between 100 km and 200 km. Hip-58 has decreased our earnings and loss of trust to helium mining. We agree to fight with cheaters but this update affect innocent people and its not fair. İ cant stop the witness with far away hotspots. İt doesnt work just nearest hotspots. Please think about this. Best regards

**Comment by capjbadger007** [comment]
Why?

**Comment by Bcagatay53** [comment]
> Why? 

There are 9 nearest hotspot in my city. And by the seaside there is a city about 130-150 km. My hotspots will witness them mostly but all invalid. And there is no beacon in the nearest hotspots. Cheaters starts at 200 km. 100 km is too low. And the other hand, why are they invalid. İ think it wouldnt be enter the beacon. İt wont be witnessed. Sorry about my bad english

**Comment by capjbadger007** [comment]
> > Why?
> 
> There are 9 nearest hotspot in my city. And by the seaside there is a city about 130-150 km. My hotspots will witness them mostly but all invalid. And there is no beacon in the nearest hotspots. Cheaters starts at 200 km. 100 km is too low. And the other hand, why are they invalid. İ think it wouldnt be enter the beacon. İt wont be witnessed. Sorry about my bad english

Your hotspot being too far away is not a reason. You are too far away from sensors, so why would you be paid for not covering them? 100km is double what sensors can send. 

Your English is fine. :)

**Comment by Bcagatay53** [comment]
> > > Why?
> 
> > 
> 
> > There are 9 nearest hotspot in my city. And by the seaside there is a city about 130-150 km. My hotspots will witness them mostly but all invalid. And there is no beacon in the nearest hotspots. Cheaters starts at 200 km. 100 km is too low. And the other hand, why are they invalid. İ think it wouldnt be enter the beacon. İt wont be witnessed. Sorry about my bad english
> 
> 
> 
> Your hotspot being too far away is not a reason. You are too far away from sensors, so why would you be paid for not covering them? 100km is double what sensors can send. 
> 
> 
> 
> Your English is fine. :)


How can i stop  the witness with far hotspots. İt can make it with stock antenna on 130 km. My and nearest hotspots cant witness eachother. Just send beacon to far away hotspots and witness with them. All invalid. There are to many state distance between them 150 km and too many hotspot owners want to carry hotspots to the city center. İn will affect the transmit scales. İ cant understand who won something with hip58

**Comment by Bcagatay53** [comment]
Thats the reason


For example , i have 3 hotspots and in my state totally 9 hotspots. On the other hand there is a city, it’s 140 km far away and there are too many hotspots in there.  In my cities hotspots sends beacon to other city mostly , and our hotspots witnesses other cities hotspots. So too many transaction are invalid. And i see in your denylist chart, cheaters witness distance is starts at 200 km mostly. So its clear between 100 km and 200 km. Hip-58 has decreased our earnings and loss of trust to helium mining. We agree to fight with cheaters but this update affect innocent people and its not fair. İ cant stop the witness with far away hotspots. İt doesnt work just nearest hotspots. Please think about this. Best regards

**Comment by waveform06** [comment]
One example of a lost income from HIP58 is not a reason to change it.

**Comment by Bcagatay53** [comment]
> One example of a lost income from HIP58 is not a reason to change it.

There are too many examples but just i write here

**Comment by MarinStoyanov** [comment]
100 km is too little. I support setting a limit of 200 km. There are many examples, even with a 1.8dBi antenna, sometimes if it is high it goes 100 km.

**Comment by ilovespectra** [comment]
I agree **100km is too close**, but 200km could easily be too far. Let's not throw the baby out with the bathwater. 

125km is a reasonable extension. **Why?** 

-There still needs to be incentive to perfect hotspot placement
-Sensors/nodes with aftermarket antennas can easily communicate over 100km
-Taking the crown from height is counterintuitive from an RF perspective
-The code was written to invalidate rather than exclude 100km+ witnesses
-An additional 25km wouldn't benefit gamers
-There are many of off-grid or rural hotspots being negatively impacted

I suggest possibly modifying the language of this proposal to suggest 125km as the new PoC distance limit, and adding a lot more "why" than less valid witnesses.

**Comment by Bcagatay53** [comment]
I see other hotspots and they try to witness +150 km. But they dont try 5-10 km hotspots. I think something changed about algorithm. I wrote reasons which i catch. Maybe some other people add them. I talk to many people in some community chat groups and they mostly tell about invalid witnesses. Authorities will choose the correct distance i think. But this issue must think again on it.

**Comment by biffbash** [comment]
I do support a more realistic limit of 200km ,HIP-58 has no technical reasoning its a poorly designed blanket one size fits all.

1) there ARE sensors that go over 100KM 
https://shop.s5system.com/collections/iot-sensors/products/lsn50v2-s31b-lorawan-temperature-humidity-sensor-dragino-smart-sensor-au915-s5-system

2) Different regions have different legal Transmit DB levels
 eg 16db vs 30db, and thus can transmit further in higher power regions generally before the receivers radio gets a minimum signal below approx -130db    in HIP-58 this isn't brought into consideration.

3)different frequencies used by different regions - they attenuate differently
![unknow1n](https://user-images.githubusercontent.com/100178734/163719692-f5e3444f-7109-47f7-af4d-c9b310169261.png)
above is a picture of FSPL  on 433mhz and 928mhz , 433mhz travels 6db better (in layman's terms  after traveling 100km the 433mhz signal is ~4x stronger than a 928mhz signal)
NB: to be fair FSPL is unrealistic perfect case scenario and signal wont to travel as well in RL 

4) FSPL graph above clearly illustrates that at 100km  with a start of +16db or+30db , the loss you should expect will be greater that -95 to -102 db , and since helium radio witness packets(sensor or PoC) below -130db  that still leaves alot of legitimate users being penalised by HIP-58.

5) Gamers were not affected by HIP-58 , they simply reasserted themselves inside 100km as gamers would do.
legitimate users that had invested into good setup locale/terrain are adversely affected - see 1) there are sensor that work at this range
Rural users who had decent setup location in low populated areas also adversely affected.

6) even on the github hip-58 main summary  is misleading: 
https://github.com/helium/HIP/issues/384
"Although a Helium Hotspot may be able to see PoC beacons
greater than 100 km, there are no current use cases at this range."
the existence of 1) clearly invalidates this.

7) the HIP vote information is misleading : 
"The distance is doubled to 100km in order to incentivize new Hotspot placements"
When current devices can clearly function over 100km+ , as pointed above.

and further incorrectly claiming  "This limit is further supported by the fact that most sensor deployments have a practical maximum distance of 30-50km" comparing cheaper devices and with no external aerial connectors to quality devices with external aerials there is a difference.


It may better serve the community to actually have on the vote page a Pro and Con information section by different authors  on the HIP being voted on and not skewed in order of presentation etc.
that way both sides of the argument are present instead of currently the proponent author being able present a one sided argument and voters will be able to make better informed choice.

**Comment by Bcagatay53** [comment]
Thank you for your research and information. This article will accept from the authorities as strong reasons. Thank you again

**Comment by biffbash** [comment]
HIP 58 shouldve come under in: hip-49-lorawan-subregion-max-eirp

HIP-49 should eventually control not just the region max EIRP but the max witness distance, heres why:

1) HIP-49  knows the frequency being used  and will know the distance that frequency is able to travel

2) HIP-49 has the regions frequency max DB  and will be able to calculate how far a unit should be able to transmit in perfect conditions using FSPL while still being within local TX compliance requirements, (this in turn will discourage those who go past legal transmit maximums and encourage compliance locally.)

HIP58 should've never been a separate HIP, essentially is overriding functions of HIP-49 that will give us our limits ,thats why we need HIP-59 to Pass  then we can work on it being implemented into HIP-49.

**Comment by evandiewald** [comment]
Based on the pre-HIP 58 state of the network (see this [figure](https://user-images.githubusercontent.com/37876940/161453891-f712991d-3d6b-44c5-bf09-e9a4a5fcf394.png) in the HIP): 
- Pre-HIP 58, about **1%** of hotspots garnered more than 10% of their witness events from beacons > 100km away.
- About **0.5%** of hotspots garnered more than 50% of their witness events from > 100km
- Of this segment, a significant portion of the affected hotspots are already on the denylist. So, we're talking on the order of **0.25%** of hotspots that are not on the denylist AND would lose half their POC rewards. 
- The small number of gamers using this exploit were capturing dozens of > 100km witness events a day (see [here](https://user-images.githubusercontent.com/37876940/163713868-59752613-41c4-486a-90ad-851873046849.png) - 200+ events over a 4000-block sample). The good news is that these disproportionate rewards will now be returned to the network.

I think we are all happy to see a sanity check on the valid witness distances - it will be nice to no longer see absurd beacon activity on explorer. **A 100km limit reduces the false positive rate to the order of statistical noise (3-4 standard deviations)**, which seems like a reasonable goal on a network this size, but I would be interested to see the **data-driven** interpretations for other limits. Whether the proposed change is for 125, 150, 200km, etc., it is difficult to evaluate the argument based on anecdotes and singular examples. Consider the following questions in your analysis: 

- How would X limit affect the 700,000+ hotspots on the network overall?
- Will the impact on gaming be worth the false positive rate? 
- How *reliable* is LoRaWAN coverage at such distances for *most* devices? 
    - According to [the LoRa Development portal](https://lora-developers.semtech.com/documentation/tech-papers-and-guides/lora-and-lorawan/#:~:text=The%20name%2C%20LoRa%2C%20is%20a,areas%20(line%20of%20sight)), the reliable limits are 5 - 15km depending on LOS.
    - This [study](https://ieeexplore.ieee.org/document/8584548) reports a maximum reliable limit of 10km using the 868MHz frequency.
    - This [series of case studies](https://smartmakers.io/en/lorawan-range-part-2-range-and-coverage-of-lorawan-in-practice/) maxed out around 14-15km, even on a device mounted on a 45km pole.
    - The [world record](https://www.thethingsnetwork.org/article/lorawan-distance-world-record) for a LoRa transmission (on a balloon flight) is 741km!
- If I set the limit at X km, how would I convince someone that it shouldn't be X+1 km, even if they have an example of a packet traveling that far?

**Comment by stefz1980** [comment]
Hello
I expressed my concerns and arguments in hip58 channel but to sum up:
Hip58 was a hip designed to mainly try to stop cheaters. Unfortunately not only it could be easily overcome in a matter of time by gamers but it also hit without any distinction legit miners who can witness Farther than 100km. I did some calculation with some app provided in the hip58 channel and based on them it was averaging a reduction from 7 to 15% of reward reduction coming from witnessing above 100km. My company manages a fleet of 22 miners which got installed in rural areas to provide coverage to sensors used by farmers and agriculture professionals. I m aware that main usage and goal of helium is to provide sensor coverage which is not able to go more than 30-40km but at the same time it is pretty unfair to hit without any distinction legit and legal miners which not only provide this coverage but can witness also at a distance greater than 100km... I can also personally testify the facts that few clients we have, after having seen this change of rules on the run felt kind of disappointed and felt unfair treatment towards their investment...therefore as a consequence decided for the moment not to invest into the installations of more miners and more sensors. I didn't mention that area where this installs took place are mainly agriculture areas far from the cities, which get main rewards from the cities which are on average 40-50km far away and occasionally from farther witnessing. At the end, proof of coverage of other farther miners shouldn't be treated as gaming due to the fact that this is mainly possible with standard equipment just adding stronger antenna (6-8), placing hotspots 
 in a high location with great line of sight. In the hip58 channel i provided datas and numbers with photos of few installs affected. The 200km limit would be much more accurate due to the fact that even if it s not common to be reached such a distance it gives much higher tolerance for certain setups which can reach farther witnessing than average miners without being defined gamers...

**Comment by biffbash** [comment]
thats another interesting point you mentioned is channel noise, we have duplex here , not simplex and even a regional diffrence such as that, or the channel bandwith and transmit time is going o make a big difference.
so the noise limit you mentioned may be more applicable to areas that are simplex once saturation hits, but not every country is.

**Comment by volgne** [comment]
> Change the distance limit to 200 For example , i have 3 hotspots and in my state totally 9 hotspots. On the other hand there is a city, it’s 140 km far away and there are too many hotspots in there. In my cities hotspots sends beacon to other city mostly , and our hotspots witnesses other cities hotspots. So too many transaction are invalid. And i see in your denylist chart, cheaters witness distance is starts at 200 km mostly. So its clear between 100 km and 200 km. Hip-58 has decreased our earnings and loss of trust to helium mining. We agree to fight with cheaters but this update affect innocent people and its not fair. İ cant stop the witness with far away hotspots. İt doesnt work just nearest hotspots. Please think about this. Best regards

I absolutely agree with you. I have an average of 120 whitness per day and 60-70 are 100 kilometers away. Especially since I've already tried so hard to put it in this position. Now, with the new update, my position, which was an advantage in the past, has now become a disadvantage. They have to do it at least 150 or 200 kilometers or I will sell and boycott all the coins I have. I'm sorry for my bad english
Best regards Volkan güneş

**Comment by florinstefan19** [comment]
We have invested time and money in equipment to cover those areas where are no hotspots, I have few hotspots at 100-150km from nearest city and they are helping the network, they cover areas with agricultural land and forest and I see no reason why I should loose witnesses as they are at 110-150km away. This was not stated in the rules before and because those people who don't care and don't know how to make a good setup voted for 100km I think the rule should be reviewed and increased. Those who are gaming the system should be stopped in other ways not limiting the witness distance. probably will be better if you set income limit to max 2hnt/day/hotspot as not many are earning more and the network will not be that badly affected by gamers.

**Comment by 6LazLo1** [comment]
Karadeniz bölgesi çok dağlık sinyaller uzakta kalıyor 100 km den sonra sı için gerekli izinleri karşılayanlara açılmalı  .200 km ideal 👍

**Comment by StinkendeGilbert** [comment]
Hello,

In my opinion there must also be a greater distance then 100KM !
I think 200KM would be fine or at least 150 KM !
there are too many users and locations affected in this . Here i also rent some towers on seaside and before i easy could hit UK from Belgium 128 KM distance , this i lost now ! 

It's not right that sensors don't hear over 100 KM as there are sensors that hear easy over 100 KM as mentioned above here already !

I can follow the thing to fight against cheaters but in my opinion too many good an normal users are affected in this and it should be modified to at least 150 km but i prefer 200KM

Don't forget helium encourgaged people to build great setups and think on those in small rural environments that have build a setup and depends on the further away hotspots to witness.

I think in this phase of the network building it's not good to already limit the distance.

So please consider it to bring it to at least 150 a 200 km ! as this is a real joke now and too many good users are affected.
Maybe not all big affected but it's not fair imo. The excuse sensors only hear 100 KM is also a joke. If you know a bit about RF and Lora you should know before it was called LongFi ! 

There are enough people with knowledge that can confirm it's way easy for some sensors to hear more then 100 KM 
also in future there will come more sensors that will hear bigger and longer so it's a bad move imo.

please consider this to modify the distance.

i can agree modifications are needed and normal in building an network but last months it's seems a big joke with the constantly changing stuff and me and a lot of people start losing trust and faith in the helium.

We need to admit that in this phase of the project it's about getting HNT and witnesses too, offcourse later on it will change and it's based on data but that's future !

thanks for consider it and maybe let's find a middle way and put it to 150 KM if 200 is too much or you think cheaters will take more advantage. 

In my opinion it's also not the way to fight against cheaters but this is another discussion !

thx & grtz

stinkende gilbert

**Comment by tanselsacikara** [comment]
It should definitely be increased to 200 km. Most of the cheaters affect the ones after 200 km.  
pity for people who do everything right and position them so they can see farther

**Comment by gkmel** [comment]
> > Niye ya?
> 
> Şehrimde en yakın 9 etkin nokta var. Ve deniz kenarında 130-150 km civarında bir şehir var. Sıcak noktalarım çoğunlukla onlara tanık olacak ama hepsi geçersiz. Ve en yakın noktalarda işaretçi yok. Hile yapanlar 200 km'de başlar. 100 km çok az. Ve diğer yandan, neden geçersizler. Beacon'a girilmeyeceğini düşünüyorum. Şahit olmayacak. kötü ingilizcem için özür dilerim

yes I have the same problem, I connect to the opposite city of the sea, but there are too many invalid witnesses, my position is good, I am not cheating :(

**Comment by gkmel** [comment]
> Sıcak noktaların olmadığı alanları kapsayacak ekipmana zaman ve para yatırdık, en yakın şehirden 100-150km uzaklıkta birkaç sıcak noktam var ve ağa yardım ediyorlar, tarım arazisi ve ormanı olan alanları kaplıyorlar ve neden göremiyorum. 110-150km uzakta oldukları için tanıkları serbest bırakmalıdır. Daha önce kurallarda bu belirtilmemişti ve umurunda olmayan ve iyi bir kurulum yapmayı bilmeyenler 100km için oy verdiği için kuralın gözden geçirilip arttırılması gerektiğini düşünüyorum. Sisteme oyun oynayanlar, tanık mesafesini sınırlamadan başka şekillerde durdurulmalıdır. Gelir sınırını maksimum 2hnt/gün/hotspot olarak ayarlarsanız muhtemelen daha iyi olacaktır çünkü pek çoğu daha fazla kazanmıyor ve ağ oyunculardan o kadar kötü etkilenmeyecek. Bence 200km oyuncuların gelirini artırmayacak, dürüst madencilere yardımcı olacaktır.
![Ekran Görüntüsü (1)](https://user-images.githubusercontent.com/103924526/163774495-ab1a324b-dc5e-4500-826d-287be595a097.png)

my location is nice and high but i have too many invalid witnes 110 km is enough for me :(

**Comment by zagora4** [comment]
Reducing the maximum distance for the witness is not the solution to the problem, it is just putting a small patch on the problem of cheating.
Those who cheat the network will surely find another way to circumvent the newly introduced rules and a others that has nothing to do with it can throw their setups in the trash because neither the network nor they benefit more from them.
There are certainly better ways to solve the problem ... Harness the meanders and help grow the network.

**Comment by Snowist** [comment]
I support increasing the limit, ie 125km, or 150 km max. In rural areas, this limit creates problems in reaching crowded hotspots. At least 100 km and beyond are not counted in 14 witnesses when the broadcast beacon is made.

**Comment by waveform06** [comment]
2 things
1) This is not a vote, so saying you support the increase as your earnings are less doesn't actually add anything to the HIP
2) I've yet to see proof/evidence that sensors can work 100Km and or that there is a business that uses that model.
- Showing a spec of a device that "could" work at that distance is like believing MPG figures for cars. What is the real world fuel economy    
- Saying you provide coverage over lots of agricultural land or forest does not mean you could pick up ground based sensors there. Would anyone invest 10,00s in sensors if the only hotspots that could pick them up were 100-200km away. No. They would place local offgrid based hotspots 

So to get this listened to you need to provide evidence of good scenarios working at the 100km range so PoC could be doubled. And then I might vote for it.

**Comment by stefz1980** [comment]
Adrian
Saying you provide coverage over lots of agricultural land or forest does not mean you could pick up ground based sensors there. Would anyone invest 10,00s in sensors if the only hotspots that could pick them up were 100-200km away. No. They would place local offgrid based hotspots.

This is exactly what my company does. Not only our miners provide coverage for sensors used by farmers mainly but they could also witness Farther than 100km due to their location...now all this witnessing is not valid anymore. Clients are unhappy. Few of them already decided not to expand further...sadly

**Comment by 6LazLo1** [comment]
Why are there 12 or 15 dbi antennas, we pay money to buy an antenna, there is no cheating, the system should find the cheaters, there is no 100 km limit, and non-criminals also suffer.

**Comment by waveform06** [comment]
> Why are there 12 or 15 dbi antennas, we pay money to buy an antenna, there is no cheating, the system should find the cheaters, there is no 100 km limit, and non-criminals also suffer.

Because Helium is not the only user of 433/868/915/923 MHz

**Comment by StinkendeGilbert** [comment]
There are for sure sensors that can go over 100 KM, many of you forget that Lora was LongFi before
I can give multiple examples for my case : the locations on the Sea side in Belgium give great coverage and was the plan to work also for boats on the Nort Sea between Belgium and uk. this is +- 125 to 150 km now sadly all those became invalid and it brings me down to deploy more sensors on boats and sea too ( there is more then land only)

Also it's not fair that now in some cases from the 14 'seeing' 8 are invaldi due this new distance limit. Means they been chosen for the 'lottery' but are invalid and don't count and take the tickets of others.

As mentioned above in more rural areas it's a big lose....

I can agree in crowded places and city's 100 KM should be enough but not all live and deploy in world cities or crowded area's 
there are a lot of cases like farmers, seaside , mountains and so on who do not any profit with this new hip

please consider a higher distance like 150  KM ...

thanks !

**Comment by StinkendeGilbert** [comment]
> > Why are there 12 or 15 dbi antennas, we pay money to buy an antenna, there is no cheating, the system should find the cheaters, there is no 100 km limit, and non-criminals also suffer.
> 
> Because Helium is not the only user of 433/868/915/923 MHz

agree , but this will cost more clients / customers then already existing system with no distance limit
also many forget helium encouraged people to build great and massive crazy setups so all this constantly changes are not good imo . This is imo pure a move against cheating and as mentioned already it will stay cat and mouse as long the core problem is not fixed. Also if we go trough the cheaters we see 90 % is from more then 200 KM ....
In good perfect wheater conditions it's not that difficult to go over 100 KM with a great setup .....
And there are enough sensors that pick it up from this distance too.

I was plan to bring some new sensor on market too but with a limit of 100 KM i feel i'm bring down the quality i want setup and give with this ....

**Comment by ilovespectra** [comment]
> There are for sure sensors that can go over 100 KM, many of you forget that Lora was LongFi before…
> 
> please consider a higher distance like 150 KM ...
> 
> thanks !

agreed.

I don’t under stand folks argument for ShoRaWan, there are a lot of folks disregarding the Lo. While a lot of good ‘why’ is being provided _for_ the case of a 25-50km increase, not seeing any homework being provided in why a 25-50km increase would be so beneficial to spoofers that we shouldn’t even consider it. 

What if the folks firm on 100km are sour their furthest witness is in their neighboring res 8, and that they’ve got a “more-pie-for-me” mentality because rather than suffering from HIP 58, there _is_ more pie being left at the table. And when folks like me are renting tower space to make sure we’re providing the best possible coverage to the network, I think it’s important to continue to reward good hotspot placement for a network bootstrapped by incentive. _At least_ not punish it. 

*incrase to 125km plz*

**Comment by abhay** [comment]
This thread is full of anecdotes and no actual analysis that's in line with this suggestion.

> Based on the pre-HIP 58 state of the network (see this [figure](https://user-images.githubusercontent.com/37876940/161453891-f712991d-3d6b-44c5-bf09-e9a4a5fcf394.png) in the HIP):
> 
> * Pre-HIP 58, about **1%** of hotspots garnered more than 10% of their witness events from beacons > 100km away.
> * About **0.5%** of hotspots garnered more than 50% of their witness events from > 100km
> * Of this segment, a significant portion of the affected hotspots are already on the denylist. So, we're talking on the order of **0.25%** of hotspots that are not on the denylist AND would lose half their POC rewards.
> * The small number of gamers using this exploit were capturing dozens of > 100km witness events a day (see [here](https://user-images.githubusercontent.com/37876940/163713868-59752613-41c4-486a-90ad-851873046849.png) - 200+ events over a 4000-block sample). The good news is that these disproportionate rewards will now be returned to the network.
> 
> I think we are all happy to see a sanity check on the valid witness distances - it will be nice to no longer see absurd beacon activity on explorer. **A 100km limit reduces the false positive rate to the order of statistical noise (3-4 standard deviations)**, which seems like a reasonable goal on a network this size, but I would be interested to see the **data-driven** interpretations for other limits. Whether the proposed change is for 125, 150, 200km, etc., it is difficult to evaluate the argument based on anecdotes and singular examples. Consider the following questions in your analysis:
> 
> * How would X limit affect the 700,000+ hotspots on the network overall?
> * Will the impact on gaming be worth the false positive rate?
> * How _reliable_ is LoRaWAN coverage at such distances for _most_ devices?
>   
>   * According to [the LoRa Development portal](https://lora-developers.semtech.com/documentation/tech-papers-and-guides/lora-and-lorawan/#:~:text=The%20name%2C%20LoRa%2C%20is%20a,areas%20(line%20of%20sight)), the reliable limits are 5 - 15km depending on LOS.
>   * This [study](https://ieeexplore.ieee.org/document/8584548) reports a maximum reliable limit of 10km using the 868MHz frequency.
>   * This [series of case studies](https://smartmakers.io/en/lorawan-range-part-2-range-and-coverage-of-lorawan-in-practice/) maxed out around 14-15km, even on a device mounted on a 45m pole (edit: 45m).
>   * The [world record](https://www.thethingsnetwork.org/article/lorawan-distance-world-record) for a LoRa transmission (on a balloon flight) is 741km!
> * If I set the limit at X km, how would I convince someone that it shouldn't be X+1 km, even if they have an example of a packet traveling that far?

Instead I'm seeing a "but my antenna setup optimizes for longer PoC activity" conversation. If you have an actual HIP that you can write, please do and include actual data. The good thing is that the implementation of the distance limit today has kept all the data on chain so you can actually include that data in your HIP.

**Comment by waveform06** [comment]
> What if the folks firm on 100km are sour their furthest witness is in their neighboring res 8, and that they’ve got a “more-pie-for-me” mentality because rather than suffering from HIP 58, there _is_ more pie being left at the table. And when folks like me are renting tower space to make sure we’re providing the best possible coverage to the network, I think it’s important to continue to reward good hotspot placement for a network bootstrapped by incentive. _At least_ not punish it.
> 
So I have a challenge for this assumption "renting tower space to make sure we’re providing the best possible coverage to the network". Doing this  IS creating best possible PoC coverage but I'm not convinced it's the best coverage for the network, which is about Sensors.

Do I believe sensors can go over 100km?. Yes. (Stick a hotspot 700m high and you can get Line of Sight sure) But other than people saying they can there is no evidence or examples so far shown so far of implementations.

**Comment by ilovespectra** [comment]
I 100% agree this is absolutely not a HIP, and just a thread of conjecture. I apologize for adding to the opinion pool with no data, I realize the conversation is based on PoC not network use. I was naive in assuming the sensors would have nearly the range on average that hotspots cover, realizing now that’s a massive area. The tower isn’t tall, but it’s on a hill. It sends data 24/7, but certainly at the rate of PoC. 

I’m willing to evolve and lower the antenna, and forego the tower rental all together if it means more nodes being able to communicate with my hotspot. I’m not desperate for HNT, I really enjoy the hardware/geek factor and love Helium as an ecosystem. I simply wanted to provide my personal experience that I myself use sensors on the helium network with aftermarket antennas that could have to communicate over 25km to receive the data in the downlinks I send it. It’s not impossible is all I really should have said. Thanks for your feedback folks, I apologize again for the utter absence of numbers in here. 

Power to the People’s Network 🎈

**Comment by Bcagatay53** [comment]
İs anybody can say how to notify the issue to the authorities?

**Comment by jamiew** [comment]
@Bcagatay53 thanks for your submission. This repository is for HIP documents and is not a general discussion forum. Please see below for how to submit. I'd be happy to have you speak on this topic at this week's community call if you are interested – noon ET on Weds https://dewi.org/community-call – please let me know here or on Discord `jamiedubs#0001`

If you'd like to continue with this, please write and submit a proposal. You should follow the format and process prescribed in HIP7, [Process for managing Helium Improvement Proposals](https://github.com/helium/HIP/blob/master/0007-managing-hip-process.md)

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

**Comment by hdtvspace** [comment]
Now, in summer 2023 there are many hotspots offline because of low earnings. We need a longer range to 150 or 200 km to optimize and enhance the network and get more PoC. It is really sad to see so many " Max distance exceeded“ in the logs…  Please change / fix it. Thanks in advance.

**Comment by capjbadger007** [comment]
> Now, in summer 2023 there are many hotspots offline because of low earnings. We need a longer range to 150 or 200 km to optimize and enhance the network and get more PoC. It is really sad to see so many " Max distance exceeded“ in the logs… Please change / fix it. Thanks in advance.

There is no point in giving POC rewards to hotspots that are too far away to pass data from sensors.

**Comment by hdtvspace** [comment]
> > Now, in summer 2023 there are many hotspots offline because of low earnings. We need a longer range to 150 or 200 km to optimize and enhance the network and get more PoC. It is really sad to see so many " Max distance exceeded“ in the logs… Please change / fix it. Thanks in advance.
> 
> There is no point in giving POC rewards to hotspots that are too far away to pass data from sensors.

1. The max range of LoRaWAN is approx. 700 km
2. You didn’t understand why the network has so much offline hotspots now
3.  Read and understand post —> https://github.com/helium/HIP/issues/389#issuecomment-1100899334

**Comment by capjbadger007** [comment]
> > > Now, in summer 2023 there are many hotspots offline because of low earnings. We need a longer range to 150 or 200 km to optimize and enhance the network and get more PoC. It is really sad to see so many " Max distance exceeded“ in the logs… Please change / fix it. Thanks in advance.
> > 
> > 
> > There is no point in giving POC rewards to hotspots that are too far away to pass data from sensors.
> 
> 1. The max range of LoRaWAN is approx. 700 km
> 2. You didn’t understand why the network has so much offline hotspots now
> 3. Read and understand post —> [HIP-58 Poc distance limit incrase to 200 km #389 (comment)](https://github.com/helium/HIP/issues/389#issuecomment-1100899334)

1. Sensors don't transmit that far.
2. You have shown no proof of why there are offline hotspots.
3. You are once again assuming sensors broadcast the same as hotpots.

The issue is dead and the community voted. Move on.

**Comment by StinkendeGilbert** [comment]
I think we all know why many hotspots are offline and stopped 'believe' in
this project

Almost no real ussage or not enough in the time we are
denylist that hits a lot of innocent people and after months still not
being reviewed or removed
since the move to solana another drop in rewards / earnings for miners /
Hotspot owners
and we can keep continue ...
it was a nice ride for those who where in early and the money has been made
by the early investors who had the balls to sell ar +- 50 usd
you see this enough in the markets ... altough we are in a bear market as
we know when other coins or let us say most coins pump HNT don't do that
much anymore. the coin is not bought like before either and the money came
from the mass deployment of hotspots on a short time

you can keep tell a lot of stuff but you need to face some things as they
are :)

it's been a joke longer then today

goodluck all and think twice next time a nice project with good story come
across ;)

cheers


Op vr 9 jun 2023 om 20:12 schreef capjbadger007 ***@***.***>:

**Comment by hdtvspace** [comment]
> > > > Now, in summer 2023 there are many hotspots offline because of low earnings. We need a longer range to 150 or 200 km to optimize and enhance the network and get more PoC. It is really sad to see so many " Max distance exceeded“ in the logs… Please change / fix it. Thanks in advance.
> > > 
> > > 
> > > There is no point in giving POC rewards to hotspots that are too far away to pass data from sensors.
> > 
> > 
> > 
> > 1. The max range of LoRaWAN is approx. 700 km
> > 2. You didn’t understand why the network has so much offline hotspots now
> > 3. Read and understand post —> [HIP-58 Poc distance limit incrase to 200 km #389 (comment)](https://github.com/helium/HIP/issues/389#issuecomment-1100899334)
> 
> 1. Sensors don't transmit that far.
> 2. You have shown no proof of why there are offline hotspots.
> 3. You are once again assuming sensors broadcast the same as hotpots.
> 
> The issue is dead and the community voted. Move on.

Wrong, my hotspot witnessed up2 350 km, but … " Max distance exceeded“ 
Its not all about data andd your wring thinking…

[   ] You have understand why private persons installed helium hotspots for hundred of euros. 

EOT

**Comment by capjbadger007** [comment]
> Wrong, my hotspot witnessed up2 350 km, but … " Max distance exceeded“ Its not all about data and your wrong thinking…
> 
> [ ] You have understand why private persons installed helium hotspots for hundred of euros.
> 
> EOT

You witnessed a *hotspot*. No sensor is going to transmit that far.

**Comment by MintakaB** [comment]
Hi, I am not sure whether is going to be an update on distance limits but my experience shows that 100Km in my area fall short. I run sensors going beyond >100Km because the sea in the middle allow to reach that far and the lack of gateways in remote places. To me a figure around 150Km seems way more practical in general and also why not a POC depending on how crowded is the area. If the area is poorly covered increase the limit to something like <200Km max. cheers
