### ISSUE TITLE
HIP 62: PoC Witness IP Check

### ISSUE THREAD

**Issue by hiptron** [helium/HIP#422]
- Author(s): [@H-Baguette](https://github.com/h-baguette)
- Start Date: 2022-05-24
- Category: Technical
- Original HIP PR: https://github.com/helium/HIP/pull/414
- Tracking Issue: https://github.com/helium/HIP/issues/422

# Rendered view

Read the HIP:

https://github.com/helium/HIP/blob/main/0062-poc-witness-ip-check.md

# Summary

Prevent spoofing by checking each witness's IP address against the beacon's IP address and other witnesses' IP addresses, while still allowing witnesses sharing the same IP address as the beacon to be considered valid under specific yet rather accessible conditions.

Additionally, prevent spoofing farms from hiding their miners behind VPNs by heavily restricting the use of VPNs on Helium hotspots.

**Comment by kevinbrooksby** [comment]
I echo these similar concerns, I have a couple of wide spread point-to-multi-point ubiquiti airmax sites w/ legitimate hotspots deployments at these locations that are linked over 5-15km wireless bridge links that are providing valuable network coverage while hairpinning back through same LAN to WAN internet gateway. NOT cool at all if this tramples my rather unique solution, I know I may be an edge case but some thoughtful engineering needs to be taken into account for us types of 'outside the box' thinkers with the skillet and aptitude to deploy such novel architectures which benefit 'the people's network'

**Comment by biffbash** [comment]
you should not be penalising people for having proper point to point setups.
https://ubiquitistore.com.au/product/ubiquiti-nanobeam-ac-19dbi-5ghz-802-11ac-gen2-450-mbps-range-15-km-nbe-5ac-gen2-au/

and CGNAT is present for most mobile providers and some fixed providers, so you would nerf 4g functionality ( for outdoor miners with sim cards) straight away and regular hotspots on a fixed home connection.
Public locations such as universities if on their network would face similar issues.

VPN use is legitimate also for businesses or those who live at a university or behind a NAT to NAT and for security ,

additionally for those who arent beind cgnat alot of connection the IP you receive is dynamic , so it changes when you d/c or when your IP lease ends , resulting in an innocent users getting a banned IP allocated to them.
trying to ban by IP is flawed & targetting VPNs are a terrible idea.

**Comment by karakemal80** [comment]
This hip is will be a very bad idea for detecting spoofers. You will detect innocent miners which behind cgnat or using dynamic ips. İ live in a residence of multiple blocks around 4 or 5 km Square with a public wifi for People living here.
With this hip only one hot spot can witness all others are spoofers?
You should re consider this hip for sure.
 People with this or similar scenarios will be not few,  lots of People may face this wrong spoofers detecting mechanism that hip using and they will be invalided falsely.
On average most normal home users in here are behind cgnat with a dynamic ip.
You can not expect everyone with a statik ip therefore ipv4 ips are about the finish all over the world and ipv6 is not being Used effectively.

**Comment by Cari53** [comment]
Hip 62 will do nothing but punish honest people because of cheaters, just like the 100 km rule brings. It is ignored that a different IP address can be obtained for each device. it protects cheaters and punishes honest people. How Does; If my device throws a beacon and 2-3 or more of those cheaters' devices witness, their testimony will be invalid, but what will my beacon reward be?
I don't know if it's technically possible, can "location not in claimed place" be the reason for invalidity? The witness receiving device may have RSSI, SNR and (x, y, z three-dimensional position) calculated for the witness it receives. If he sends a signal from this device to his beaconer, and if these two signal values are compared, the ones outside a certain tolerance value are considered invalid. 
If a lora device communicates with three gateways, it can detect its location, the greater the number of gateways contacted, the higher the location accuracy.
By making use of Lora signals, the actual location of each device can be determined. Of course, this is possible by writing an algorithm. I guess the helium team can write code algorithm for this. By comparing the position information of the device antenna recorded in the system and the position determined from the lora signals, it can be interpreted with a certain limit tolerance value.
 This is the healthiest and surest solution. why don't they try to use it.
IP checking does not give the desired result, it only punishes honest people.

**Comment by andrebrei** [comment]
I have some concerns about this proposal in its current form that it will penalize valid hotspot owners in an disproportional way compared to "cheaters". 

I'm one of those hotspot owners who's GeoIP is constantly misreported to be in the wrong country except for high intelligence accuracy (but expensive) GoeIP providers. Note that there is no requirement for an IP to be assigned an geographic location. The whois registration is the location of owning entity and can be vastly different from the actual device location. Everything else is either educated guessing or private discussions.

Similarly in an different location the only viable option is cellular (4G/5G) via one specific provider. That provider's CGNNAT is so bad (connection lifetime, IP affinity) that it is not usable without VPN even for simple web browsing. So depending on VPN detection this may cause my hotspot to be flagged too (in this case VPN GeoIP and actual location is in the same country but the IP has an high potential to be flagged as "data center").

On the other side, how much of an effort is it for an cheater to adapt? The majority of the cost is likely for the first device (e.g. getting an static IP enabled) while cost comes rapidly down per device with additional devices (e.g. get an full network routed). I suspect the cost increase will be too low to substantially reduce the amount of cheaters.

With that it feels like that it has an potential to reduce real coverage more than it penalizes cheaters.
Have there been any statistics compiled yet in terms of how many hot spots will be impacted in total and tried to establish an split of false positives/unclear/"cheaters"?

I'm not sure CGNAT has an real impact here right now because the p2p requirement for full miners will be broken already. That might change with the p2p requirement going away eventually.
Similarly I don't think IPv6 will really help in this discussion because it will lower the difficulty for cheaters in the same way that it allows good hotspots to gain an unique IP.

Last I'd wonder if other options have been considered like an incentive to build a "trust" network or "war drive" hotspots to either independently assert or challenge an location/coverage. Like done for other technologies e.g. cellmapper for cellular.
