### ISSUE TITLE
HIP 70: Scaling the Helium Network

### ISSUE THREAD

**Issue by edakturk14** [helium/HIP#471]
## HIP 70: Scaling the Helium Network

- Author(s): Helium Core Developers
- Start Date: 2022-08-30
- Category: Technical
- Original HIP PR: https://github.com/helium/HIP/pull/470
- Tracking Issue: [this](https://github.com/helium/HIP/issues/471)
- Status: In Discussion

## Summary

In this HIP, we propose a new approach to Proof-of-Coverage and Data Transfer Accounting by moving this responsibility to oracles and, thereby, reducing the complexity required for operating a blockchain that supports the Helium Network. Through these actions, we believe we can allow for more reliable data transfer and more consistent and predictable Proof-of-Coverage activity. 

With the move to more “oracled” activity on chain, we believe that the simplification allows us to select a more scalable Layer 1 for the Helium community, specifically Solana. Integration of the Helium tokens (HNT, DC, IOT, and MOBILE, initially) into the Solana ecosystem additionally provides Helium wallet holders access to a variety of applications, governance mechanisms, and other utilities not available natively on our sovereign L1.

We acknowledge that this change removes the need for staked validators operating block production and challenge creation as they do today. That said, we expect that HNT stakers will migrate their positions towards securing current and/or future subDAOs and participating in governance through the vote-escrow token based system proposed in [HIP 51](https://github.com/helium/HIP/blob/main/0051-helium-dao.md). Removal of the staked validator reward also returns the full 6.85% of HNT emissions back to the miner pool, benefitting Hotspot owners on all subDAOs. In the first year alone, this is estimated to be over 2 million more HNT rewarded for Hotspot activity.

We consider these changes as complementary to the changes proposed in HIP 51 and a necessary set of changes to more easily implement some of the redemption and governance mechanisms proposed in HIPs 51, [52](https://github.com/helium/HIP/blob/main/0052-iot-dao.md), and [53](https://github.com/helium/HIP/blob/main/0053-mobile-dao.md). We additionally expect that more protocols will be attracted to participate in the Helium ecosystem because of the move to a more widely used Layer 1 blockchain.

## Rendered View 

https://github.com/helium/HIP/blob/main/0070-scaling-helium.md

**Comment by TheRealJohnMac50** [comment]
After the cooldown period is over, I do not see why it is "expected" for validators (vals) to not sell off their HNT. VeHNT/subDAO governance is both brilliant and important. Additionally, there will be staking rewards, and subDAO rewards. (Not seeing any other reasons for vals to want to continue staking their HNT, please correct me if I missed something.) I'm sure that many vals will not sell off their HNT. However, as things stand, there **will possibly also be many vals that do sell off their HNT**. 

As mentioned in the HIP, vals account for 38% of all HNT. Even with increased staking and subDAO rewards, I do not think the severity of the vals that will sell off their HNT (regardless of all rewards being offered) is being accounted for. Even if only 50% of vals choose to sell off their HNT, you are talking about **19% of all HNT being dumped on the market**. Even if only 25% of vals sell off their HNT, that is **9.5% of all HNT being sold off on market**. In the event that those sell offs occurred, this would theoretically cause a domino effect, that can possibly take a very long time to recover from.

Suggest implementing **various** additional methods to provide vals with reasons that result in the desire for vals to continue staking their HNT and participating with the network. 

With veHNT/subDAO governance, taking rewards, and subDAO rewards, it may not be enough to keep vals motivated to continue participating with the network. 

The potential consequences for not giving vals proper motivation to continue participating with the network, could be extremely severe.  

All that being said, this is an incredible undertaking, with (as I understand it) the motivation (as I understand it) being an incredible network upgrade.

Words cannot possibly properly express my sincere gratitude to all of you who provide endless selflessness for the good of the network. 

Thank you and please keep up the incredible work.

**Comment by harpone** [comment]
Bit of a travesty to make this vote "Solana or nothing". What happens if Solana fades into oblivion like EOS, NEO or the other Ethereum killers that nobody even remembers anymore? The vote should be between e.g. Solana, Ethereum+rollups etc. 

Also, devs should declare their bags when suggesting stuff like this. I'm going to vote NO although probably all the lemmings will vote yes.

**Comment by aJetHorn** [comment]
A drawback that was not addressed in the proposal is that validator hosts who are currently unstaked and waiting out the cooldown may have to join the aforementioned selling frenzy alongside those who unstaked during the privileged cooldown window and earned rewards for a longer period of time. I propose that vals that were unstaked before the timestamp of this announcement are given special consideration (likely, compensation) if their regular cooldown will collide with the introduction of the suggested shortened cooldown. Making this clear will also minimize the rush (today) for validator hosts to unstake aiming to gain some incentive or otherwise profit from taking an opinion on how long it will take these changes to go live (over/under 6 months minus 1 month).

Another concern I have, which is steeped in irony, is that this proposal is much more clearly written than some of the "controversial" HIPs from months past. It makes me suspect that the changes in HIP 70 are already ticketed out in a sprint board somewhere and the features are already on their way to being delivered. In other words, is this project already informally adopted and being taken beyond a feasibility testing phase without an official vote? If so, I see this as an unfair jumping of the gun from a governance perspective that will rouse suspicion. I wonder if in the future we can ask for HIPs to contain a statement of work completed, loose time-to-completion estimates, and attestations regarding conflicts of interest.

**Comment by Siegfried-B** [comment]
I believe this sentence - regarding what happens to validator rewards that won't got to validators any more - is incorrect: 
"In the first year alone, this is estimated to be over 2 million more HNT rewarded for Hotspot activity."

6,85% of emitted HNT in year 4 equals 30.000.000 * .0685 = 2.044.000 HNT that will be distributed to subDAOs.
20% of subDAO tokens (7% to Oracles, 7% to Operations Fund, 6% to veHNT stakers) in Lorawan subDAO do not go to Hotspot activity. (Percentage in MOBILE subDAO is even higher).
So, at best, 2.044.000 * .8 = 1.644.000 HNT go to Hotspots activity reward. That's lots less than 2.000.000
I am not complaining about that fact, but the numbers should be correct.

**Comment by buzzeddesign** [comment]
There are several folks that feel that Cosmos SDK is a better option than Solana for miners - there's an alternate version of this proposal in draft form as [HIP 71](https://github.com/helium/HIP/pull/472) where the architecture proposed in HIP 70 is preserved, but a recommendation of Kujira as the L1 Cosmos SDK chain is proposed instead of Solana - I encourage feedback from anyone interested in Cosmos SDK and IBC as an option to propose changes to any language on that PR and I will tag you as an author.

**Comment by wolfenhawke** [comment]
I think HIP71 is a good way to evaluate other chains for this purpose. Cosmos in this case. It would be good to add a section on measurement criteria so we can quantitatively (or as close  as possible) measure the strength of the chain choice. For instance, it is constantly noted that Solana is centralized: that is not a fixed situation due to the chain; Instead it is a dynamic of the chain being young and most full nodes being run by few entities in line with the team (at least a year ago). Solana is working to cost reduce the node requirement to have greater distribution. So, a level of sctual distribution would be a good criteria. Maybe how many full nodes? Others are latency, TPS,

**Comment by harpone** [comment]
The most important argument is if _if the chain will be around in 5-10 years_, not "muh baaags".

Most likely survivors are Bitcoin and Ethereum. Bitcoin is a no, so that leaves Ethereum (or maybe Cosmos). Ethereum L2 fees are very low, so you could use e.g. Arbitrum, zksync, Starknet etc. for scaling. Fees are <1% of base layer fees.

**Comment by Hempfele** [comment]
I also agree that moving to solana could be viewed as a "gamble" - especially for it's centralization.
Staying decentralized should be the most important aspect to be considered when choosing the chain to migrate to.

**Comment by cvolkernick** [comment]
I don't inherently have any significant complaints about Solana and don't have any significant knowledge on any of the alternative L1s, however at the risk of sounding conspiratorial, it seems worth consideration that the Muliticoin capital team is highly invested in both helium and Solana, and plays a considerable part in the development of both. They are also obviously very involved in Nova Labs (authors of this HIP) and author many of the larger more involved HIPs that are ultimately implemented.

Again, I'm not trying to point fingers or make accusations, simply pointing out the fairly obvious incentives.

**Comment by dereknelson** [comment]
!!!!!! reemphasizing @harpone & @Dsingis comments. 
@cvolkernick advocates for the devil well about it being easier to collaborate, but i think "better collaboration" is an extremely weak argument relative to the how much more centralized helium would become because of parent orgs incentives.

i'm not writing solana off by any means, but i'd say we'll know within the next 1-2 years whether it's going to be around longterm, let alone decentralized.

i'd be disappointed if nova labs chose to innovate on solana & i'd pray that another extremely capable org takes over helium development on a l2 ethereum chain. whether its decentralization (nodes, validation etc.), tx cost, or the developer ecosystem, ethereum is the only compelling chain moving the needle on **all three**.

**Comment by cvolkernick** [comment]
Would be ideal if somehow system architecture was designed such that offchain activity was "interoperable" with multiple chains, but not sure if that's even feasible or not.

**Comment by dereknelson** [comment]
town hall discussing this HIP at 4:00pm EST https://discord.gg/DwHBXmnT?event=1014283301248311338

**Comment by Nickeytheblade** [comment]
All for it, the more we can merge with everyone and get things moving the better!

**Comment by leogaggl** [comment]
> Would be ideal if somehow system architecture was designed such that offchain activity was "interoperable" with multiple chains, but not sure if that's even feasible or not.

I do agree @cvolkernick - or at least separate the (structural change) HIP to be independent of the blockchain tech!

The vote should probably be for an architectural change and how to ensure the outcome this distributed, transparent and well governed. The eventual chain is a secondary issue.

**Comment by PJEstrada** [comment]
Why not go with the Cosmos SDK instead? Gives you the flexibility of a custom application blockchains and not be at the mercy of the Solana stability issues.

**Comment by mv2woods** [comment]
"A more thorough analysis of the variety of options considered is forthcoming but to briefly summarize our reasoning, we evaluated several options. "

Not sure why this wasn't included in the original posting of HIP70... Seems like the decision to use Solana was made in haste and/or with a predetermined outcome. I'd be interested to see this "thorough analysis". You did very little to highlight the objective benefits and drawbacks of Solana vs others. I feel like this should have been a much bigger part of the initial proposal than it was.

**Comment by vocaloidat** [comment]
> So it's either Solana (a centralized chain, prone to outages, chain-halts, instability and it being in beta) or nothing? What a joke, honestly. If you really wanted to put this up to a vote, then you'd make it a vote between all possible smart contract crypto currencies. Why Solana? Why not Polkadot? Why not Avalanche? Why not Algorand? Why not Cosmos? Why not Cardano? Why not Ethereum (post sharding maybe?)
> 
> Why not find the best that fits to the Helium project? Why compromise on stability and decentralization? Isn't Helium all about decentralized infrastructure? Why Solana? Have they not proven themselves to be unreliable in the last time? Have they not shown how easy their wallets are exploited? I simply don't get it. Did you guys get paid by them or something?

Effective suggestions, I also think that ALGORAND, COSMOS and other options should also be added.

**Comment by JFVE** [comment]
here is an example for "scale" terrain of helium´s co-founder                                      
![Emrit_sch](https://user-images.githubusercontent.com/103133838/188568780-40a88d1f-b342-4e8b-8a54-74381a9e2630.jpg)

**Comment by 0xBooler** [comment]
hey guys, Uddhav from Friktion (https://friktion.fi) here. been getting up to speed of the migration to Solana and very excited for how much design space this opens up with DeFi! would love to chat with any folks interested in this and share how we're thinking about this at Friktion ⚡

**Comment by arul-borderless** [comment]
Copy for the formal email request sent to Helium Foundation board members and the head of Operations

9/11/22

To

Tushar Jain, Chris Bruce, Jamie Wilkinson, Scott Sigel
Helium Foundation Board members and Head of Operations

Copy 

Amir Haleem, CEO of Nova Labs Inc

Subject: HIP 70 - Proposal to evaluate other L1 chains before voting

HIP 70 proposal to scale the Helium network is very critical and most significant for the near-term and long-term success of the Helium network. We agree that Helium cannot maintain and operate its own Layer1 blockchain.  Finding another Layer1 blockchain that can handle proof of coverage and data transfer in the most reliable and secure manner is very critical. 

Nova Labs core developers picked Solana as the right choice without giving an equal opportunity for many of the other Layer1 blockchains to propose their solution. The core developers neither published any kind of detailed supporting analysis of the decision with pros and cons. It is impossible for the community, third-party developers, staking providers, and other users to understand the pros and cons of moving to Solana without such detailed analysis and transparency. 

Blockchains are software-based networks in which rules should be immutable and drastic changes like the remotion of validators or trusting its consensus to a different technology or blockchain would require detailed analysis, testing, security audits, third-party experts/advisors' opinions, and approval of all the stakeholders of that network with a tremendous level of public transparency. 

Moreover, Helium introduced many changes as part of HIP 51 that are complex to understand by the majority of community members and have an economic impact on HIP 70. The market doesn’t like uncertainty and it is already reflected as the HNT price went below $5 after the introduction of HIP 70. 

Tushar Jain, founding board member of Helium Foundation said, Helium moving to another Layer1 blockchain would be the largest chain migration ever by every metric like users, market cap, daily transactions, etc. That is correct and Helium migration got attention from most of the layer1 blockchains. Since we are running the Helium ecosystem fund at Borderless. most of these layer 1 blockchain co-founders and core developers reached out to us and are very keen to propose better solutions and also support the Helium team during the migration




I had multiple conversations with below individuals/groups in the last several days 

Chris Bruce, ex-VP of Product for Helium Systems, Inc. and the current board member of the Helium Foundation
Sean Carey, Co-founder, and ex-CTO of Helium Systems, Inc (Nova Labs)
Several hotspot miners and validators of Helium Network
Co-founders and core developers of Algorand, Polygon, Moonbean / Polkadot

Most of them agree with the concerns and demand more transparency and believe that we can have a better solution by entertaining proposals from other Layer1 blockchains. The current proposed solution in HIP 70 is centralized Oracle for Proof of coverage and data transfers which are the 2 most critical and unique aspects of the Helium network. Most of them believe that we need to have a more decentralized approach to these Oracle and should give a chance for other Layer1 blockchains to present solutions to address this. 

In the past Helium community considered the Cosmos as one of the alternative options.  I also analyzed the debate between Jack Zampolin (core developer of Cosmos) and Kyle Samani (Managing Partner of MultiCoin Capital) on App chains and also spoke to several Web3 thought leaders and cryptographic experts. The broader  community should watch the debate at https://www.youtube.com/watch?v=7abafmCCyik

After thoughtful analysis and discussion with many stakeholders, below is the proposal to the Helium Foundation board: 

We formally propose to the Helium Foundation board that they should evaluate the proposal from other leading Layer 1 blockchains first before submitting the HIP 70 proposal to the community vote. 

The core developers should work under the guidance of the Helium Foundation board and the committee to properly evaluate the proposals from other Layer1 blockchains. 

Helium Foundation should clearly outline evaluation criteria and be transparent in its analysis. 

Helium Foundations should come out with their top 2 picks on Layer 1 blockchains with pros and cons and submit to vote by the community with full transparency. The voting should not happen until the foundation have a clear plan/path to decentralizing the Oracles - Proof of Coverage and Data Transfers 

At the least, this will bring better innovation and solutions to the problems Helium blockchain is currently facing. I understand that it is time critical for the Helium network to decide on the right layer1 blockchain at the earliest. So between me and my partners running the Helium ecosystem fund at Borderless, we can assure the foundation to provide complete support to get this done in an expedited manner.

In order to provide more transparency and less uncertainty in the community, the Helium foundation should be funded with more capital and employ the core devs directly. This will allow the foundation to maintain the direction of the blockchain in a more open independent way and in more decentralized manner.

There is nothing against Solana as a layer 1 blockchain, but we are afraid the outcome of the HIP 70 vote cannot be fair unless more than one blockchain is presented to the community to choose from. I’m voicing my opinion as a fan of the Helium network and I’m always here along with my partners from Borderless to support any way possible to make it a meaningful and sustainable migration.

Sincerely, 

Arul Murugan 
Chairman and Managing Partner
Borderless Capital 


PS: Arul’s involvement in the Helium ecosystem as a builder, investor, and supporter 

* Founding board member of Helium Foundation
* One of the largest miners/builders of People’s network since its inception in August 2019, and 
* One of the largest investors both as an individual and as a professional fund manager running the Helium Ecosystem fund 
   at Borderless

**Comment by arul-borderless** [comment]
> > So it's either Solana (a centralized chain, prone to outages, chain-halts, instability and it being in beta) or nothing? What a joke, honestly. If you really wanted to put this up to a vote, then you'd make it a vote between all possible smart contract crypto currencies. Why Solana? Why not Polkadot? Why not Avalanche? Why not Algorand? Why not Cosmos? Why not Cardano? Why not Ethereum (post sharding maybe?)
> > Why not find the best that fits to the Helium project? Why compromise on stability and decentralization? Isn't Helium all about decentralized infrastructure? Why Solana? Have they not proven themselves to be unreliable in the last time? Have they not shown how easy their wallets are exploited? I simply don't get it. Did you guys get paid by them or something?
> 
> Effective suggestions, I also think that ALGORAND, COSMOS and other options should also be added.

Valid concern. See the proposal from Borderless Capital running the Helium ecosystem fund submitted to Helium Foundation board members

**Comment by arul-borderless** [comment]
> Copy for the formal email request sent to Helium Foundation board members and the head of Operations
> 
> 9/11/22
> 
> To
> 
> Tushar Jain, Chris Bruce, Jamie Wilkinson, Scott Sigel Helium Foundation Board members and Head of Operations
> 
> Copy
> 
> Amir Haleem, CEO of Nova Labs Inc
> 
> Subject: HIP 70 - Proposal to evaluate other L1 chains before voting
> 
> HIP 70 proposal to scale the Helium network is very critical and most significant for the near-term and long-term success of the Helium network. We agree that Helium cannot maintain and operate its own Layer1 blockchain. Finding another Layer1 blockchain that can handle proof of coverage and data transfer in the most reliable and secure manner is very critical.
> 
> Nova Labs core developers picked Solana as the right choice without giving an equal opportunity for many of the other Layer1 blockchains to propose their solution. The core developers neither published any kind of detailed supporting analysis of the decision with pros and cons. It is impossible for the community, third-party developers, staking providers, and other users to understand the pros and cons of moving to Solana without such detailed analysis and transparency.
> 
> Blockchains are software-based networks in which rules should be immutable and drastic changes like the remotion of validators or trusting its consensus to a different technology or blockchain would require detailed analysis, testing, security audits, third-party experts/advisors' opinions, and approval of all the stakeholders of that network with a tremendous level of public transparency.
> 
> Moreover, Helium introduced many changes as part of HIP 51 that are complex to understand by the majority of community members and have an economic impact on HIP 70. The market doesn’t like uncertainty and it is already reflected as the HNT price went below $5 after the introduction of HIP 70.
> 
> Tushar Jain, founding board member of Helium Foundation said, Helium moving to another Layer1 blockchain would be the largest chain migration ever by every metric like users, market cap, daily transactions, etc. That is correct and Helium migration got attention from most of the layer1 blockchains. Since we are running the Helium ecosystem fund at Borderless. most of these layer 1 blockchain co-founders and core developers reached out to us and are very keen to propose better solutions and also support the Helium team during the migration
> 
> I had multiple conversations with below individuals/groups in the last several days
> 
> Chris Bruce, ex-VP of Product for Helium Systems, Inc. and the current board member of the Helium Foundation Sean Carey, Co-founder, and ex-CTO of Helium Systems, Inc (Nova Labs) Several hotspot miners and validators of Helium Network Co-founders and core developers of Algorand, Polygon, Moonbean / Polkadot
> 
> Most of them agree with the concerns and demand more transparency and believe that we can have a better solution by entertaining proposals from other Layer1 blockchains. The current proposed solution in HIP 70 is centralized Oracle for Proof of coverage and data transfers which are the 2 most critical and unique aspects of the Helium network. Most of them believe that we need to have a more decentralized approach to these Oracle and should give a chance for other Layer1 blockchains to present solutions to address this.
> 
> In the past Helium community considered the Cosmos as one of the alternative options. I also analyzed the debate between Jack Zampolin (core developer of Cosmos) and Kyle Samani (Managing Partner of MultiCoin Capital) on App chains and also spoke to several Web3 thought leaders and cryptographic experts. The broader community should watch the debate at https://www.youtube.com/watch?v=7abafmCCyik
> 
> After thoughtful analysis and discussion with many stakeholders, below is the proposal to the Helium Foundation board:
> 
> We formally propose to the Helium Foundation board that they should evaluate the proposal from other leading Layer 1 blockchains first before submitting the HIP 70 proposal to the community vote.
> 
> The core developers should work under the guidance of the Helium Foundation board and the committee to properly evaluate the proposals from other Layer1 blockchains.
> 
> Helium Foundation should clearly outline evaluation criteria and be transparent in its analysis.
> 
> Helium Foundations should come out with their top 2 picks on Layer 1 blockchains with pros and cons and submit to vote by the community with full transparency. The voting should not happen until the foundation have a clear plan/path to decentralizing the Oracles - Proof of Coverage and Data Transfers
> 
> At the least, this will bring better innovation and solutions to the problems Helium blockchain is currently facing. I understand that it is time critical for the Helium network to decide on the right layer1 blockchain at the earliest. So between me and my partners running the Helium ecosystem fund at Borderless, we can assure the foundation to provide complete support to get this done in an expedited manner.
> 
> In order to provide more transparency and less uncertainty in the community, the Helium foundation should be funded with more capital and employ the core devs directly. This will allow the foundation to maintain the direction of the blockchain in a more open independent way and in more decentralized manner.
> 
> There is nothing against Solana as a layer 1 blockchain, but we are afraid the outcome of the HIP 70 vote cannot be fair unless more than one blockchain is presented to the community to choose from. I’m voicing my opinion as a fan of the Helium network and I’m always here along with my partners from Borderless to support any way possible to make it a meaningful and sustainable migration.
> 
> Sincerely,
> 
> Arul Murugan Chairman and Managing Partner Borderless Capital
> 
> PS: Arul’s involvement in the Helium ecosystem as a builder, investor, and supporter
> 
> * Founding board member of Helium Foundation
> * One of the largest miners/builders of People’s network since its inception in August 2019, and
> * One of the largest investors both as an individual and as a professional fund manager running the Helium Ecosystem fund
>   at Borderless

Below is the link to the google doc if anyone wants to provide their comments 

https://docs.google.com/document/d/1wc8g2GJC8PNst_m1G2A_4Y464RNOk8Oo5kDW61s_6F0/edit?usp=sharing

**Comment by Tristannn1337** [comment]
I voted against HIP 70. Solana is a siloed and unreliable network with no advantage over the Ethereum ecosystem. I suggest Arbitrum Nova (https://nova.arbitrum.io/).

**Comment by Meirperetz** [comment]
@edakturk14 suggestion: why not to use a completely decentralized git repository for the Oracles code, just keep it decentralized and efficient.
this collaboration of people under the people's network is just incredible to see so let's keep it.

**Comment by vincenzospaghetti** [comment]
@Meirperetz Hi Meir - I like this idea. I took over Eda's role as HIP Editor. Would you be interested in defining this further in a HIP proposal? Or let's discuss this more on Discord. My initial questions are: Aren't all git repositories already 'decentralized'? Are you asking for a public repository for the oracles?

**Comment by Meirperetz** [comment]
> @Meirperetz Hi Meir - I like this idea. I took over Eda's role as HIP Editor. Would you be interested in defining this further in a HIP proposal? Or let's discuss this more on Discord. My initial questions are: Aren't all git repositories already 'decentralized'? Are you asking for a public repository for the oracles?

Yeah exactly, public repository on ipfs.

**Comment by vincenzospaghetti** [comment]
This has been implemented. Please see contracts on the Solana blockchain or visit this Repo: https://github.com/helium/helium-program-library.
